### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by rogomezh** [IcaliaLabs/sepomex#15]
How I am supposed to use the service?

https://sepomex-api.herokuapp.com/api/v1/zip_codes
or
https://sepomex.icalialabs.com/api/v1/zip_codes

first option works, but apparently with old data, and second options gives me a timeout error with no response

**Comment by kurenn** [comment]
@rogomezh Yeah, the first one due to heroku limitations on the database, it doesn't have all the data, in the mean time, you can use that one, but the second one is the one you should be using at last, but currently is down, sorry about the troubles this may occur, I'll let you know as soon as it is up!

**Comment by kurenn** [comment]
You are now able to use the http://sepomex.icalialabs.com/api/v1/zip_codes it is back online! sorry for the inconvenience
